spring:
  thymeleaf:
    cache: false
  datasource:
    ##Mysql数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.99.177:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Nenu666$
    ##连接池配置
    hikari:
      #连接池名称
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间
      idle-timeout: 1800000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的链接自动提交
      auto-commit: true
      #连接最大存活时间
      max-lifetime: 1800000
      #连接超时时间，默认也是30秒
      connection-timeout: 30000
      #测试链接的sql语句
      connection-test-query: SELECT 1

##Mybatis-plus配置信息
mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置数据返回类型别名
  type-aliases-package: com.oppo.seckilldemo.pojo

logging:
  level:
    com.oppo.seckilldemo.mapper: debug